[versions]
agp = "8.7.1"
bcprovJdk18on = "1.79"

[libraries]
bcprov-jdk18on = { module = "org.bouncycastle:bcprov-jdk18on", version.ref = "bcprovJdk18on" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
